-- QUESTIONS

-- 1. What is the gender breakdown of employees in the company?

SELECT GENDER,count(*) AS COUNTS FROM HR WHERE AGE >=18 
group by GENDER;

-- 2. What is the race/ethnicity breakdown of employees in the company?

SELECT RACE,count(*) AS COUNTS 
FROM HR 
WHERE AGE>=18 
GROUP BY RACE
ORDER BY count(*) DESC;

-- 3. What is the age distribution of employees in the company?

SELECT MIN(AGE) AS YOUNGEST,
MAX(AGE) AS OLDERS
FROM HR 
WHERE AGE>=18;

SELECT 
CASE
WHEN AGE>=18 AND AGE<=24 THEN '18-24'
WHEN AGE>=25 AND AGE<=34 THEN '25-34'
WHEN AGE>=35 AND AGE<=44 THEN '35-44'
WHEN AGE>=45 AND AGE<=54 THEN '45-54'
WHEN AGE>=55 AND AGE<=64 THEN '55-64'
ELSE '65+'
END AS AGE_GROUP,
count(*) AS COUNT
FROM HR 
WHERE AGE>=18 
GROUP BY AGE_GROUP
ORDER BY AGE_GROUP;




SELECT 
CASE
WHEN AGE>=18 AND AGE<=24 THEN '18-24'
WHEN AGE>=25 AND AGE<=34 THEN '25-34'
WHEN AGE>=35 AND AGE<=44 THEN '35-44'
WHEN AGE>=45 AND AGE<=54 THEN '45-54'
WHEN AGE>=55 AND AGE<=64 THEN '55-64'
ELSE '65+'
END AS AGE_GROUP,GENDER,
count(*) AS COUNT
FROM HR 
WHERE AGE>=18 
GROUP BY AGE_GROUP,GENDER
ORDER BY AGE_GROUP,GENDER;


-- 4. How many employees work at headquarters versus remote locations?

SELECT LOCATION,COUNT(*) AS COUNT 
FROM HR 
WHERE AGE>=18 
group by LOCATION;

-- 5. What is the average length of employment for employees who have been terminated?

SELECT
round(avg(datediff(termdate,hire_date))/365,0) AS AVG_LENGTH_EMPLOYMENT 
FROM HR
WHERE TERMDATE<=curdate() AND TERMDATE<>'0000-00-00'
AND AGE>=18;

-- 6. How does the gender distribution vary across departments and job titles?

SELECT DEPARTMENT,GENDER,COUNT(*) AS COUNT from HR 
WHERE AGE>=18 
GROUP BY DEPARTMENT,GENDER
ORDER BY DEPARTMENT;

-- 7. What is the distribution of job titles across the company?

SELECT JOBTITLE, COUNT(*) AS COUNT
FROM HR
WHERE AGE>=18 
GROUP BY JOBTITLE
ORDER BY JOBTITLE DESC;


-- 8. Which department has the highest turnover rate?
SELECT DEPARTMENT, TOTAL_COUNT,
TERMINATED_COUNTS,
TERMINATED_COUNTS/TOTAL_COUNT AS TERMINATION_RATE
FROM(
SELECT DEPARTMENT,
COUNT(*) AS TOTAL_COUNT,
SUM(CASE WHEN TERMDATE<>'0000-00-00' AND TERMDATE<=CURDATE() THEN 1 ELSE 0 END) AS TERMINATED_COUNTS
FROM HR 
WHERE AGE >= 18
GROUP BY DEPARTMENT
) AS SUBQUERY
ORDER BY TERMINATION_RATE DESC;



-- 9. What is the distribution of employees across locations by city and state?

SELECT LOCATION_STATE,COUNT(*) AS COUNT 
FROM HR 
WHERE AGE>=18 
GROUP BY LOCATION_STATE
ORDER BY COUNT DESC;

-- 10. How has the company's employee count changed over time based on hire and term dates?

SELECT
YEAR, HIRES,TERMINATIONS,HIRES-TERMINATIONS AS NET_CHANGE,
ROUND((HIRES-TERMINATIONS)/HIRES*100,2) AS NET_CHANGE_PERCENT
FROM (
SELECT YEAR(HIRE_DATE) AS YEAR,
COUNT(*) AS HIRES,
SUM(CASE WHEN TERMDATE<>'0000-00-00' AND TERMDATE<=CURDATE() THEN 1 ELSE 0 END) AS TERMINATIONS
FROM HR 
WHERE AGE>=18 
GROUP BY YEAR(HIRE_DATE)
) AS SUBQUERY 
ORDER BY YEAR ASC;

-- 11. What is the tenure distribution for each department?

SELECT DEPARTMENT, ROUND(AVG(datediff(TERMDATE,HIRE_DATE)/365),0) AS AVG_TENURE
FROM HR 
WHERE TERMDATE<=CURDATE() AND TERMDATE<>'0000-00-00' AND AGE>=18
GROUP BY DEPARTMENT ;
